# Generated by Django 3.2.10 on 2022-10-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('data_rojdeniya', models.CharField(max_length=10)),
                ('pol', models.CharField(choices=[('M', 'Мужской'), ('J', 'Женский')], default='M', max_length=1)),
            ],
        ),
    ]
