# Generated by Django 4.1.2 on 2022-10-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form01', '0002_remove_user_pol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='data_rojdeniya',
        ),
    ]
