# Generated by Django 4.1.2 on 2022-10-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form01', '0003_remove_user_data_rojdeniya'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_rojdeniya',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
