# Generated by Django 4.1.2 on 2022-10-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form01', '0004_user_data_rojdeniya'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pol',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
