# Generated by Django 4.1.2 on 2022-10-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form01', '0005_user_pol'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resultn',
            field=models.CharField(default=None, max_length=100, verbose_name='Результат'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='data_rojdeniya',
            field=models.CharField(max_length=10, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fio',
            field=models.CharField(max_length=100, verbose_name='Ф.И.О'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pol',
            field=models.CharField(max_length=20, verbose_name='Пол'),
        ),
    ]
